### ISSUE TITLE
Exception in JavaFX Application Thread during tests.

### ISSUE THREAD

**Issue by lange88** [asgill/SEM-25#40]
It doesn't occur all the time and tests still complete succesful but sometimes an exception is thrown.

Test output
```
Game started
Combo Jewels on board: 0
Game stopped
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at nl.tudelft.bejeweled.game.Game.updateSprites(Game.java:122)
	at nl.tudelft.bejeweled.game.Game$1.handle(Game.java:71)
	at nl.tudelft.bejeweled.game.Game$1.handle(Game.java:62)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:226)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:167)
	at javafx.animation.Timeline.impl_playTo(Timeline.java:176)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(InfiniteClipEnvelope.java:110)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$26(Animation.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$405(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Switch (1,6) with (1,7)

Process finished with exit code 0
```

**Comment by lange88** [comment]
I think it happens in the launchertest class when the sprite gets removed by game.stop() in the main thread and game.updateSprites() gets called by the JavaFX thread in the gameloop. Both referencing the LIST_ACTORS in the SpriteStore.

**Comment by lange88** [comment]
Travis Build:
```
Running nl.tudelft.bejeweled.LauncherTest

Xlib:  extension "RANDR" missing on display ":99.0".

java.lang.NullPointerException

	at nl.tudelft.bejeweled.sprite.Jewel$1.handle(Jewel.java:138)

	at nl.tudelft.bejeweled.sprite.Jewel$1.handle(Jewel.java:133)

	at javafx.animation.Animation.impl_finished(Animation.java:1132)

	at javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)

	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:103)

	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)

	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)

	at javafx.animation.Animation$1$$Lambda$85/1110841642.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at javafx.animation.Animation$1.timePulse(Animation.java:185)

	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)

	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)

	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:447)

	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:431)

	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$363(QuantumToolkit.java:298)

	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$60/1112756225.run(Unknown Source)

	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)

	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$45(GtkApplication.java:126)

	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$56/2001171423.run(Unknown Source)

	at java.lang.Thread.run(Thread.java:745)
```
