### ISSUE TITLE
Null pointer exceptions are sometimes thrown thrown by javaFX

### ISSUE THREAD

**Issue by pimveldhuisen** [asgill/SEM-25#54]
Game continues to work when this happens

**Comment by pimveldhuisen** [comment]
This seems to happen only when the board is out of moves

**Comment by lange88** [comment]
This happens when you're out of moves and you have a highscore. The highscore dialog asking for user input should wait for the "Game Over" animation is finished.

Stack trace:
```
ll$149(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: showAndWait is not allowed during animation or layout processing
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:328)
	at nl.tudelft.bejeweled.game.BejeweledGame.stop(BejeweledGame.java:141)
	at nl.tudelft.bejeweled.game.BejeweledGame.boardOutOfMoves(BejeweledGame.java:235)
	at nl.tudelft.bejeweled.board.Board.outOfMoves(Board.java:642)
	at nl.tudelft.bejeweled.board.Board.checkBoardCombos(Board.java:361)
	at nl.tudelft.bejeweled.board.Board.update(Board.java:768)
	at nl.tudelft.bejeweled.game.BejeweledGame.updateLogic(BejeweledGame.java:200)
	at nl.tudelft.bejeweled.game.Game$1.handle(Game.java:77)
	at nl.tudelft.bejeweled.game.Game$1.handle(Game.java:71)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:226)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:167)
	at javafx.animation.Timeline.impl_playTo(Timeline.java:176)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(InfiniteClipEnvelope.java:110)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$26(Animation.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
```

**Comment by lange88** [comment]
I think this is related to #61 . The board falsely detects there are no more moves (it doesn't take into account the falling jewels) and does a showAndWait() on the high score dialog. In the meantime the jewels are done falling and when a line disappears the implosion animation of the jewels causes the exception
