### ISSUE TITLE
Resuming a saved state throws exception

### ISSUE THREAD

**Issue by lange88** [asgill/SEM-25#62]
I don't know yet why this happened. Maybe I saved the state by exiting while jewels were still falling, I'll have do some more research

Stack trace:

```
java.io.InvalidClassException: nl.tudelft.bejeweled.board.Board; local class incompatible: stream classdesc serialVersionUID = -4528983305913297480, local class serialVersionUID = -937525219091381239
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at nl.tudelft.bejeweled.game.BejeweledGame.resume(BejeweledGame.java:306)
	at nl.tudelft.bejeweled.Launcher.launchGame(Launcher.java:101)
	at nl.tudelft.bejeweled.Launcher.start(Launcher.java:69)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at nl.tudelft.bejeweled.game.BejeweledGame.resume(BejeweledGame.java:321)
	at nl.tudelft.bejeweled.Launcher.launchGame(Launcher.java:101)
	at nl.tudelft.bejeweled.Launcher.start(Launcher.java:69)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$163(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$149(WinApplication.java:191)
	... 1 more

Process finished with exit code 1
``

**Comment by lange88** [comment]
Looks like you can save while jewels are still falling just fine

**Comment by lange88** [comment]
Have not been able to reproduce since last merges
